# Generated by Django 2.2 on 2019-04-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_tasklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
